"""add_source_to_player_game_log

Revision ID: 3d6c88294f54
Revises: e7a005bfa4ca
Create Date: 2026-04-17 13:28:39.718267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d6c88294f54'
down_revision: Union[str, Sequence[str], None] = 'e7a005bfa4ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_game_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(), server_default='mlb_api', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_game_log', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
