"""baseline

Revision ID: 792e0bd8996d
Revises: 
Create Date: 2026-04-17 11:06:44.541105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792e0bd8996d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_lineups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_date', sa.Date(), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_date')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_normalized', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('mlb_id', sa.Integer(), nullable=True),
    sa.Column('bat_side', sa.String(), nullable=True),
    sa.Column('pitch_hand', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_normalized', 'team', name='uq_player_team')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_name_normalized'), ['name_normalized'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_position'), ['position'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_team'), ['team'], unique=False)

    op.create_table('slates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('game_count', sa.Integer(), nullable=True),
    sa.Column('season_stage', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('weight_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('player_type', sa.String(), nullable=False),
    sa.Column('weights_json', sa.Text(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft_lineups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slate_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('expected_total_value', sa.Float(), nullable=True),
    sa.Column('actual_total_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['slate_id'], ['slates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draft_lineups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_lineups_slate_id'), ['slate_id'], unique=False)

    op.create_table('player_game_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('opponent', sa.String(), nullable=True),
    sa.Column('ab', sa.Integer(), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=False),
    sa.Column('rbi', sa.Integer(), nullable=False),
    sa.Column('bb', sa.Integer(), nullable=False),
    sa.Column('so', sa.Integer(), nullable=False),
    sa.Column('sb', sa.Integer(), nullable=False),
    sa.Column('ip', sa.Float(), nullable=False),
    sa.Column('er', sa.Integer(), nullable=False),
    sa.Column('k_pitching', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_date', name='uq_player_game')
    )
    with op.batch_alter_table('player_game_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_game_log_player_id'), ['player_id'], unique=False)

    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=False),
    sa.Column('pa', sa.Integer(), nullable=False),
    sa.Column('ab', sa.Integer(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('hr', sa.Integer(), nullable=False),
    sa.Column('rbi', sa.Integer(), nullable=False),
    sa.Column('sb', sa.Integer(), nullable=False),
    sa.Column('bb', sa.Integer(), nullable=False),
    sa.Column('so', sa.Integer(), nullable=False),
    sa.Column('avg', sa.Float(), nullable=True),
    sa.Column('ops', sa.Float(), nullable=True),
    sa.Column('ops_vs_lhp', sa.Float(), nullable=True),
    sa.Column('ops_vs_rhp', sa.Float(), nullable=True),
    sa.Column('iso', sa.Float(), nullable=True),
    sa.Column('barrel_pct', sa.Float(), nullable=True),
    sa.Column('ip', sa.Float(), nullable=False),
    sa.Column('era', sa.Float(), nullable=True),
    sa.Column('whip', sa.Float(), nullable=True),
    sa.Column('k_per_9', sa.Float(), nullable=True),
    sa.Column('bb_per_9', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', name='uq_player_season')
    )
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_stats_player_id'), ['player_id'], unique=False)

    op.create_table('slate_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slate_id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('mlb_game_pk', sa.Integer(), nullable=True),
    sa.Column('game_status', sa.String(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('vegas_total', sa.Float(), nullable=True),
    sa.Column('home_moneyline', sa.Integer(), nullable=True),
    sa.Column('away_moneyline', sa.Integer(), nullable=True),
    sa.Column('home_starter', sa.String(), nullable=True),
    sa.Column('home_starter_mlb_id', sa.Integer(), nullable=True),
    sa.Column('away_starter', sa.String(), nullable=True),
    sa.Column('away_starter_mlb_id', sa.Integer(), nullable=True),
    sa.Column('home_starter_era', sa.Float(), nullable=True),
    sa.Column('away_starter_era', sa.Float(), nullable=True),
    sa.Column('home_starter_whip', sa.Float(), nullable=True),
    sa.Column('away_starter_whip', sa.Float(), nullable=True),
    sa.Column('home_starter_k_per_9', sa.Float(), nullable=True),
    sa.Column('away_starter_k_per_9', sa.Float(), nullable=True),
    sa.Column('wind_speed_mph', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.String(), nullable=True),
    sa.Column('temperature_f', sa.Integer(), nullable=True),
    sa.Column('scheduled_game_time', sa.String(), nullable=True),
    sa.Column('home_team_ops', sa.Float(), nullable=True),
    sa.Column('away_team_ops', sa.Float(), nullable=True),
    sa.Column('home_team_k_pct', sa.Float(), nullable=True),
    sa.Column('away_team_k_pct', sa.Float(), nullable=True),
    sa.Column('home_bullpen_era', sa.Float(), nullable=True),
    sa.Column('away_bullpen_era', sa.Float(), nullable=True),
    sa.Column('home_starter_hand', sa.String(length=1), nullable=True),
    sa.Column('away_starter_hand', sa.String(length=1), nullable=True),
    sa.Column('series_home_wins', sa.Integer(), nullable=True),
    sa.Column('series_away_wins', sa.Integer(), nullable=True),
    sa.Column('home_team_l10_wins', sa.Integer(), nullable=True),
    sa.Column('away_team_l10_wins', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['slate_id'], ['slates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('slate_games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slate_games_slate_id'), ['slate_id'], unique=False)

    op.create_table('slate_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slate_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('card_boost', sa.Float(), nullable=False),
    sa.Column('drafts', sa.Integer(), nullable=True),
    sa.Column('real_score', sa.Float(), nullable=True),
    sa.Column('total_value', sa.Float(), nullable=True),
    sa.Column('is_highest_value', sa.Boolean(), nullable=False),
    sa.Column('is_most_popular', sa.Boolean(), nullable=False),
    sa.Column('is_most_drafted_3x', sa.Boolean(), nullable=False),
    sa.Column('batting_order', sa.Integer(), nullable=True),
    sa.Column('platoon_advantage', sa.Boolean(), nullable=True),
    sa.Column('player_status', sa.String(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('env_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['slate_games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['slate_id'], ['slates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slate_id', 'player_id', name='uq_slate_player')
    )
    with op.batch_alter_table('slate_players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_slate_players_game_id'), ['game_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_slate_players_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_slate_players_slate_id'), ['slate_id'], unique=False)

    op.create_table('draft_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lineup_id', sa.Integer(), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('slate_player_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('real_score', sa.Float(), nullable=True),
    sa.Column('slot_mult', sa.Float(), nullable=False),
    sa.Column('card_boost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['lineup_id'], ['draft_lineups.id'], ),
    sa.ForeignKeyConstraint(['slate_player_id'], ['slate_players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('draft_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_slots_lineup_id'), ['lineup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_slots_slate_player_id'), ['slate_player_id'], unique=False)

    op.create_table('player_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slate_player_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['slate_player_id'], ['slate_players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slate_player_id', name='uq_player_score_slate_player')
    )
    with op.batch_alter_table('player_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_scores_slate_player_id'), ['slate_player_id'], unique=False)

    op.create_table('score_breakdowns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_score_id', sa.Integer(), nullable=False),
    sa.Column('trait_name', sa.String(), nullable=False),
    sa.Column('trait_score', sa.Float(), nullable=False),
    sa.Column('trait_max', sa.Float(), nullable=False),
    sa.Column('raw_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['player_score_id'], ['player_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('score_breakdowns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_breakdowns_player_score_id'), ['player_score_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score_breakdowns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_breakdowns_player_score_id'))

    op.drop_table('score_breakdowns')
    with op.batch_alter_table('player_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_scores_slate_player_id'))

    op.drop_table('player_scores')
    with op.batch_alter_table('draft_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_slots_slate_player_id'))
        batch_op.drop_index(batch_op.f('ix_draft_slots_lineup_id'))

    op.drop_table('draft_slots')
    with op.batch_alter_table('slate_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slate_players_slate_id'))
        batch_op.drop_index(batch_op.f('ix_slate_players_player_id'))
        batch_op.drop_index(batch_op.f('ix_slate_players_game_id'))

    op.drop_table('slate_players')
    with op.batch_alter_table('slate_games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_slate_games_slate_id'))

    op.drop_table('slate_games')
    with op.batch_alter_table('player_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_stats_player_id'))

    op.drop_table('player_stats')
    with op.batch_alter_table('player_game_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_game_log_player_id'))

    op.drop_table('player_game_log')
    with op.batch_alter_table('draft_lineups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_lineups_slate_id'))

    op.drop_table('draft_lineups')
    op.drop_table('weight_history')
    op.drop_table('slates')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_team'))
        batch_op.drop_index(batch_op.f('ix_players_position'))
        batch_op.drop_index(batch_op.f('ix_players_name_normalized'))

    op.drop_table('players')
    op.drop_table('cached_lineups')
    # ### end Alembic commands ###
