"""add_mlb_id_index

Revision ID: e7a005bfa4ca
Revises: 792e0bd8996d
Create Date: 2026-04-17 11:07:37.088895

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e7a005bfa4ca'
down_revision: Union[str, Sequence[str], None] = '792e0bd8996d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_mlb_id'), ['mlb_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_mlb_id'))

    # ### end Alembic commands ###
